apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sandbox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-sandbox
  template:
    metadata:
      labels:
        app: k8s-sandbox
    spec:
      containers:
      - name: k8s-sandbox
        image: aus10va/k8s-sandbox:latest
        ports:
        - containerPort: 8080
